force-app/main/default/objects/Account/fields/Activa__c.field-meta.xml
<CustomField>
    <fullName>Activa__c</fullName>
    <description>Campa para indicar el estado de la cuenta Activa.</description>
    <label>Activa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Influyente</fullName>
            </value>
            <value>
                <fullName>Tomador de Decisión</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ex_Cliente__c/Ex_Cliente__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado para almacenar información de cuentas desactivadas.</description>
    <label>Ex-Cliente</label>
    <nameField>
        <displayFormat>{YY}-{0000}</displayFormat>
        <label>Ex-Cliente Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ex-Clientes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ex_Cliente__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup para relacionar un contacto</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ex-Clientes</relationshipLabel>
    <relationshipName>Ex_Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ex_Cliente__c/fields/Generado_automaticamente__c.field-meta.xml
<CustomField>
    <fullName>Generado_automaticamente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campa para indicar si el registro fue generado por automatización.</description>
    <label>Generado automáticamente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ex_Cliente__c/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <formula>TEXT(Contact__r.Rol__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Account_tgr_tst.cls
@isTest
public with sharing class Account_tgr_tst {
    static testMethod void updateAccontTst(){
        Account acc = new Account(
            Name = 'Account Dummy',
            Activa__c = 'Si',
            Phone = '3003003030'
        );
        insert acc;
        Opportunity opp = new Opportunity(
            Name = 'Opportunity Dummy',
            StageName = 'Prospecting',
            Amount = 120000,
            CloseDate = System.today(),
            AccountId = acc.Id
        );
        insert opp;
        Contact cont = new Contact(
            FirstName = 'Contact',
            LastName = 'Dummy',
            Rol__c = 'Influyente',
            AccountId = acc.Id
        );
        insert cont;
        /* Prueba Update */
        Account updateAcc = [SELECT Id, Activa__c FROM Account WHERE Id =: acc.Id];
        updateAcc.Activa__c = 'No';
        update updateAcc;
        Opportunity testOpp = [SELECT Id, Description FROM Opportunity WHERE Id =: opp.Id];
        System.assertEquals('Cerrada por Cuenta Inactiva', testOpp.Description);
        Ex_Cliente__c testExC = [SELECT Id, Generado_automaticamente__c FROM Ex_Cliente__c WHERE Contact__c =: cont.Id];
        System.assertEquals(true, testExC.Generado_automaticamente__c);
    }
}